### ISSUE TITLE
join effort with hubot-mattermost

### ISSUE THREAD

**Issue by rompic** [loafoe/hubot-matteruser#1]
please team up with https://github.com/renanvicente/hubot-mattermost

**Comment by loafoe** [comment]
@rompic the hubot-mattermost uses Webhooks which is fundamentally different from how this adapter works. I'm fine with merging the projects though. It would actually be really interesting to find out the roadmap for proper Bot users in MatterMost server.

**Comment by cacack** [comment]
+1 for both teaming and understanding proper bot users in mattermost.  I started with hubot-mattermost, but would like to be able to interact with the bot using mentions.  Looks like yours would fit that bill.

**Comment by loafoe** [comment]
@cacack yep, that was exactly my motivation to go the Web API + websocket route.

**Comment by thanosk** [comment]
@loafoe thanks for this project, I too was using hubot-mattermost and looking for a way to interact privately with the bot (which is now possible). I did open a new suggestion in [mattermost's feature idea forum](http://mattermost.uservoice.com/forums/306457-general/suggestions/12280503-bot-users) referencing proper Bot users like [Slack does](https://api.slack.com/bot-users).

**Comment by karlbateman** [comment]
@loafoe This is awesome, so much easier to get up and running. Interaction is similar to other systems and its great for testing Hubot via direct message. Thanks for this, good job :+1:
