### ISSUE TITLE
Does MATTERMOST_WSS_PORT not function?

### ISSUE THREAD

**Issue by taturou** [loafoe/hubot-matteruser#10]
When the port number of the server is not 443, the adapter is not connected even if MATTERMOST_WSS_PORT is set.
I tried it with 8443 and 8065.

Thank you for awesome product!

**Comment by loafoe** [comment]
@taturou did you try it with the latest 3.3.1 release? The `master` branch contained a bug which also used the WSS port override for the *https* connection, that has been fixed recently. 
Please let me know if it works for you. Do note that *MATTERMOST_WSS_PORT* is explicitly for the WebSocket connection only.

**Comment by Vhex** [comment]
On the latest 3.3.1 release I have what I think is the same issue.  My https connections are on port 8444 (proxied to mattermost) so the initial connection won't go through.

If I specify the mattermost host as mydomain.example.com:8444 then the initial connection goes through, but websockets tries wss://mydomain.example.com:8444:443/api/v3/users/websocket

Setting that string to empty still tries wss://mydomain.example.com:8444:/api/v3/users/websocket which also won't work (note the extra colon).

So it sounds like what needs to happen is to allow you to specify a different HTTP/HTTPS port as well as the WSS port.

**Comment by loafoe** [comment]
@taturou please try with latest `master`. @Vhex added ability to make the http port configurable.
