### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by funzie19** [loafoe/hubot-matteruser#11]
I have been trying to get this up an running for the past three days now. I have tried both Mattermost 3.3 and 3.2. I am able to get the bot logged into the rooms as seen with the green icons over the username, however none of the actions work. For example if I run it with the shell adapter it works perfectly. But using the matteruser adapter does not. It looks like the bot just sits there in the chat. I would really like to get this setup. I have used the regular web hook mattermost adapter and been successful with that. Below is a debug of the last instance I had running:

> $ bin/hubot -a matteruser
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Logging in...
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG POST /users/login
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Websocket URL: ws://mattermost.kregloh.com:443/api/v3/users/websocket
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Logged in as user "vina3" but not connected yet.
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG GET /users/initial_load
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG Found 2 teams.
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG Testing bots == bots
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG Found team! wox7dqdyat8zdbb58a147c6cgr
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG GET /users/profiles/wox7dqdyat8zdbb58a147c6cgr
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG GET /teams/wox7dqdyat8zdbb58a147c6cgr/channels/
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Connecting...
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Error: Error: connect ENOENT
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Reconnecting in 1000ms
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG Found 4 channels.
> [Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] DEBUG Found 2 profiles.
> [Mon Aug 22 2016 22:08:11 GMT-0400 (EDT)] INFO Attempting reconnect
> [Mon Aug 22 2016 22:08:11 GMT-0400 (EDT)] INFO Logging in...
> [Mon Aug 22 2016 22:08:11 GMT-0400 (EDT)] DEBUG POST /users/login
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] INFO Websocket URL: ws://mattermost.kregloh.com:443/api/v3/users/websocket
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] INFO Logged in as user "vina3" but not connected yet.
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG GET /users/initial_load
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG Found 2 teams.
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG Testing bots == bots
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG Found team! wox7dqdyat8zdbb58a147c6cgr
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG GET /users/profiles/wox7dqdyat8zdbb58a147c6cgr
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG GET /teams/wox7dqdyat8zdbb58a147c6cgr/channels/
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG Found 4 channels.
> [Mon Aug 22 2016 22:08:12 GMT-0400 (EDT)] DEBUG Found 2 profiles.

**Comment by loafoe** [comment]
@funzie19 the only odd think I can spot in your log is the following:

`ws://mattermost.kregloh.com:443/api/v3/users/websocket`

port `443` would suggest a secure websocket  connection. Can you doublecheck this is OK? The symptoms you describe are in line with a broken websocket connection. Can you log in OK with the bot user from a web browser?

**Comment by campbellr** [comment]
I actually ran into what appears to be the same problem after upgrading to Mattermost 3.3 and hubot-matteruser 3.3.1

Everything was working perfectly before with the combination of Mattermost 3.0 and hubot-matteruser 3.1.1

**Comment by funzie19** [comment]
I've tried with both port 443 and 80 for the web socket. The installation that returns this error does not have a certificate therefore everything is over port 80. I suspect the error may lie with:
>[Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Connecting...
[Mon Aug 22 2016 22:08:10 GMT-0400 (EDT)] INFO Error: Error: connect ENOENT

When I try with an installation that has a valid SSL certificate it successfully connects and does a ping, but after x amount of time or when somebody starts typing into the chat it immediately returns with the error I described in https://github.com/loafoe/mattermost-client/issues/19

**Comment by loafoe** [comment]
I just pushed a fix for loafoe/mattermost-client#19. Are you able to test it with this fix? If it works can you also please post the logs? It looks like the server is returning some data over the websocket which I'm not handling yet.

**Comment by loafoe** [comment]
@campbellr are you able to share some debug log output for the MM 3.3 / HM 3.3.1 setup?

**Comment by funzie19** [comment]
@loafoe Pretty much the same error as before
>[Wed Aug 24 2016 20:13:43 GMT-0400 (EDT)] INFO ping
[Wed Aug 24 2016 20:13:43 GMT-0400 (EDT)] ERROR TypeError: Cannot read property 'text' of undefined
  at Client.onMessage (/home/joseph/vina3/node_modules/mattermost-client/src/client.coffee:224:20, <js>:295:28)
  at WebSocket.<anonymous> (/home/joseph/vina3/node_modules/mattermost-client/src/client.coffee:159:13, <js>:218:22)
  at WebSocket.emit (events.js:98:17)
  at Receiver.ontext (/home/joseph/vina3/node_modules/ws/lib/WebSocket.js:841:10)
  at /home/joseph/vina3/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/home/joseph/vina3/node_modules/ws/lib/Receiver.js:371:5)
  at /home/joseph/vina3/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/home/joseph/vina3/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.opcodes.1.finish (/home/joseph/vina3/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/home/joseph/vina3/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/home/joseph/vina3/node_modules/ws/lib/Receiver.js:103:24)
  at CleartextStream.realHandler (/home/joseph/vina3/node_modules/ws/lib/WebSocket.js:825:20)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:458:13)

**Comment by loafoe** [comment]
@funzie19 that's weird, can you please paste the code on this line:

/home/joseph/vina3/node_modules/mattermost-client/src/client.coffee:224

**Comment by campbellr** [comment]
> are you able to share some debug log output for the MM 3.3 / HM 3.3.1 setup? 

I think my 'me too' might have been a false alarm. It turned out that `hubot help` (my "go to" test command) stopped working (not sure why yet), but everything else seems to work. So probably not the same issue, sorry. I'll let myself out...

**Comment by funzie19** [comment]
Not sure why it didn't grab the code changes when I re-did the bot after your commit. But I manually added the change to the script, here is the output:

>[Thu Aug 25 2016 13:00:50 GMT-0400 (EDT)] DEBUG Found 2 profiles.
[Thu Aug 25 2016 13:00:50 GMT-0400 (EDT)] DEBUG Found 4 channels.
[Thu Aug 25 2016 13:00:53 GMT-0400 (EDT)] DEBUG Received unhandled message type: undefined
[Thu Aug 25 2016 13:00:53 GMT-0400 (EDT)] DEBUG { team_id: 'raho6b1xojb6pkm87od8ssamdr',
  channel_id: '6t3drw8q7fdkpn4ymwcyjiz13a',
  user_id: 's77siufxabypdmu7xnam38tcpo',
  action: 'typing',
  props: { parent_id: '' } }
[Thu Aug 25 2016 13:00:59 GMT-0400 (EDT)] DEBUG Received unhandled message type: undefined
[Thu Aug 25 2016 13:00:59 GMT-0400 (EDT)] DEBUG { team_id: 'raho6b1xojb6pkm87od8ssamdr',
  channel_id: '6t3drw8q7fdkpn4ymwcyjiz13a',
  user_id: 's77siufxabypdmu7xnam38tcpo',
  action: 'typing',
  props: { parent_id: '' } }
[Thu Aug 25 2016 13:01:01 GMT-0400 (EDT)] DEBUG Received unhandled message type: undefined
[Thu Aug 25 2016 13:01:01 GMT-0400 (EDT)] DEBUG { team_id: 'raho6b1xojb6pkm87od8ssamdr',
  channel_id: '6t3drw8q7fdkpn4ymwcyjiz13a',
  user_id: 's77siufxabypdmu7xnam38tcpo',
  action: 'posted',
  props:
   { channel_display_name: 'Town Square',
     channel_type: 'O',
     mentions: '["c9epeiinn3d67q7k6ncixn6s9w"]',
     post: '{"id":"jieiisxonbn57q58mbpyx11ucc","create_at":1472145179233,"update_at":1472145179233,"delete_at":0,"user_id":"s77siufxabypdmu7xnam38tcpo","channel_id":"6t3drw8q7fdkpn4ymwcyjiz13a","root_id":"","parent_id":"","original_id":"","message":"vina help","type":"","props":{},"hashtags":"","filenames":[],"pending_post_id":"s77siufxabypdmu7xnam38tcpo:1472145103277"}',
     sender_name: 'jkregloh',
     team_id: 'raho6b1xojb6pkm87od8ssamdr' } }

**Comment by loafoe** [comment]
@funzie19 Ah, it seems the above log capture was done with Mattermost 3.2.0 or earlier? 
Can you confirm? If so, can you upgrade the server to 3.3 and try again?

**Comment by jokefaker** [comment]
Same issue at first floor.
MM: version 3.3, run in a docker 
MU version: 3.3.1, run locally

export MATTERMOST_HOST=localhost
export MATTERMOST_GROUP=group
export MATTERMOST_USER=account
export MATTERMOST_PASSWORD=psw
export MATTERMOST_TLS_VERIFY=false
export MATTERMOST_USE_TLS=false
export MATTERMOST_LOG_LEVEL=debug

MU error log:
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Logging in...
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG POST /users/login
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Websocket URL: ws://localhost:443/api/v3/users/websocket
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Logged in as user "sobot" but not connected yet.
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG GET /users/initial_load
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG Found 1 teams.
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG Testing souban == souban
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG Found team! ohsndkb8u38y5xiik88qyh8rnh
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG GET /users/profiles/ohsndkb8u38y5xiik88qyh8rnh
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG GET /teams/ohsndkb8u38y5xiik88qyh8rnh/channels/
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Connecting...
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Error: Error: read ECONNRESET
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] INFO Reconnecting in 1000ms
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG Found 2 channels.
[Mon Aug 29 2016 09:51:39 GMT+0800 (CST)] DEBUG Found 2 profiles.
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] INFO Attempting reconnect
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] INFO Logging in...
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG POST /users/login
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] INFO Websocket URL: ws://localhost:443/api/v3/users/websocket
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] INFO Logged in as user "sobot" but not connected yet.
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG GET /users/initial_load
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG Found 1 teams.
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG Testing souban == souban
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG Found team! ohsndkb8u38y5xiik88qyh8rnh
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG GET /users/profiles/ohsndkb8u38y5xiik88qyh8rnh
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG GET /teams/ohsndkb8u38y5xiik88qyh8rnh/channels/
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG Found 2 channels.
[Mon Aug 29 2016 09:51:40 GMT+0800 (CST)] DEBUG Found 2 profiles.

But the MM print nothing in logs with debug log level :(

**Comment by funzie19** [comment]
@loafoe I updated the version of Mattermost and it works great now. However that is for an SSL install. If I try a non-ssl install I still get `INFO Error: Error: read ECONNRESET` like @jokefaker is also describing.

**Comment by maruTA-bis5** [comment]
I use nodejs v0.10.46 on CentOS6 and get `INFO Error: Error: read ENOENT`.
nodejs v0.10.16 installed from EPEL.

I re-installed nodejs using [this instruction](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) and works fine for non-ssl Mattermost install.

**Comment by loafoe** [comment]
Please upgrade to latest `3.5.1` release of both Mattermost server and hubot-matteruser. Please reopen if you still encounter issues.
