### ISSUE TITLE
Question: why do we add this.robot.name before the message when DM

### ISSUE THREAD

**Issue by jgarec** [loafoe/hubot-matteruser#110]
Hi @loafoe,

i was wondering why we need to add username in this case : 
https://github.com/loafoe/hubot-matteruser/blob/e62fbbed0e3f153ea8c74ce199caf9eff912c405/src/matteruser.js#L369-L371

I have a custom version on my side where i've removed this part of code. If not, it does not work with something like that :
```
robot.hear(/^!bot$/i, msg => {
...
}
```

In my case, the bot should reply only to `!bot`, not for another message like `foo bar !bot`.
But as we add username before the message, it's hard to check this.

**Comment by loafoe** [comment]
hi @jgarec this might be a leftover of past behaviour of the server. Indeed it does not look like it's strictly required and the name can probably be stripped if it's there before further processing. Accepting `PR`s for improving this..  👍🏻

**Comment by jgarec** [comment]
Hi @loafoe, could you publish a new release including #111 ?
Thx :)

**Comment by loafoe** [comment]
Will create a release shortly

**Comment by loafoe** [comment]
`v5.4.4` released
