### ISSUE TITLE
Not clear how to use this

### ISSUE THREAD

**Issue by vrenjith** [loafoe/hubot-matteruser#12]
Hi,

I setup the bot as per the instructions and the logs say that everything looks okay. And at regular intervals I see the following messages also
```
INFO ping
INFO ACK ping
```

Now, I am unable to figure out how to use the bot and what triggers any actions. Nothing happen when I DM the bot or if I do an @ mention of the bot in a channel. 

Any hints of how to actually make the bot useful?

**Comment by wargamesqcf** [comment]
I have a completly differant question is much the same, I am using the docker-compose from mattermost to start and run my chat server how do I add hubot to this? 

https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml

**Comment by loafoe** [comment]
@vrenjith if you have the bot startup with debugging enabled do you it receiving input from Mattermost? Also, is the online status of the bot account `active` when the bot joins?
