### ISSUE TITLE
I can't login hubot bot to mattermost

### ISSUE THREAD

**Issue by albertgu2016** [loafoe/hubot-matteruser#14]
MM:3.3.0
HM:3.3.1
MM: Enabled Insecure Outgoing Connections

Login failed issue.  I can login mattermost with hubot bot directly.

Why?

**Comment by loafoe** [comment]
@albertgu2016 Can you paste some of the debugging output? It could be that there is an issue with the Websocket connection

**Comment by ABitMoreDepth** [comment]
I'm hitting this issue as well, with hubot and mattermost deployed via docker (though the appropriate mattermost ports are bound to localhost).

Mattermost v3.4.0
Hubot-MatterUser v3.3.1

I can login with the hubot user manually, but the debug log from hubot is a little unhelpful:
```
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.6.0
npm info lifecycle n2ebot@0.0.0~preinstall: n2ebot@0.0.0
npm info linkStuff n2ebot@0.0.0
npm info lifecycle n2ebot@0.0.0~install: n2ebot@0.0.0
npm info lifecycle n2ebot@0.0.0~postinstall: n2ebot@0.0.0
npm info lifecycle n2ebot@0.0.0~prepublish: n2ebot@0.0.0
npm info ok
[Mon Sep 26 2016 09:50:33 GMT+0000 (UTC)] INFO Logging in...
[Mon Sep 26 2016 09:50:33 GMT+0000 (UTC)] DEBUG POST /users/login
[Mon Sep 26 2016 09:50:33 GMT+0000 (UTC)] ERROR Login call failed
[Mon Sep 26 2016 09:50:33 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
[Mon Sep 26 2016 09:50:34 GMT+0000 (UTC)] INFO Attempting reconnect
[Mon Sep 26 2016 09:50:34 GMT+0000 (UTC)] INFO Logging in...
[Mon Sep 26 2016 09:50:34 GMT+0000 (UTC)] DEBUG POST /users/login
[Mon Sep 26 2016 09:50:34 GMT+0000 (UTC)] ERROR Login call failed
[Mon Sep 26 2016 09:50:34 GMT+0000 (UTC)] INFO Reconnecting in 2000ms
[Mon Sep 26 2016 09:50:36 GMT+0000 (UTC)] INFO Attempting reconnect
[Mon Sep 26 2016 09:50:36 GMT+0000 (UTC)] INFO Logging in...
[Mon Sep 26 2016 09:50:36 GMT+0000 (UTC)] DEBUG POST /users/login
[Mon Sep 26 2016 09:50:36 GMT+0000 (UTC)] ERROR Login call failed
[Mon Sep 26 2016 09:50:36 GMT+0000 (UTC)] INFO Reconnecting in 3000ms
```

**Comment by ABitMoreDepth** [comment]
Some further debugging looks like Mattermost 3.4 uses a different API end point?
send a manual post request to /api/v3/users/login gets me further, but I hit a 400 about the password being left blank.

Should I raise a separate issue for this [here](https://github.com/loafoe/mattermost-client)?

**Comment by loafoe** [comment]
@ABitMoreDepth please upgrade to latest `3.5.1` of both Mattermost server and hubot-matteruser. Reopen this ticket if you still encounter this issue. Thanks for the feedback!
