### ISSUE TITLE
Not possible to use several groups/teams?

### ISSUE THREAD

**Issue by mberthelier** [loafoe/hubot-matteruser#15]
Hi,

Would it be possible to make a multi-instance script, where groups could be separated by a coma for instance?

Currently, we can have only 1 group/team per hubot instance. We use different teams in our organization and we would like to be able to have hubot user for all groups (even if we have to change variable each time).

**Comment by loafoe** [comment]
@mberthelier I would need to investigate. I can imagine that there is a lot of code in hubot that assumes there is only one single user list so supporting several groups/teams would have to be done as transparantly as possible. Most likely  at the mattermost-client level even. In any case I think it probably requires quite a bit of refactoring. Not something I will pick up soon I'm afraid, but will happily merge any code that moves us towards that goal.

**Comment by loafoe** [comment]
It looks like the internals of hubot will not support this. Love to be proven wrong though.
