### ISSUE TITLE
Question/Suggestion: why mattermost-client, not Mattermosts own Javascript Driver?

### ISSUE THREAD

**Issue by ThetaGamma** [loafoe/hubot-matteruser#16]
Dear Loafoe
Dear all

As far as I understood, we need _mattermost-client_ as an MM-API-Implementation for this hubot plugin. So we're limited to those calls implemented in mattermost-client, right? Wouldn't it make sense to use the original mattermost Javascript Driver found [here](https://github.com/mattermost/mattermost-driver-javascript)? As far as I understood, all necessesary API calls are implemented there.

Cheers 
TG

**Comment by loafoe** [comment]
Hi @ThetaGamma,

At the time of creating the adapter the Javascript driver was not available as a separate package. Will definitely check it out soon though! Thx! Pull requests accepted too! :-)

**Comment by ThetaGamma** [comment]
Hi

Unfortunately I'm not a good coder and the documentation of the JS-Driver is almost not existent. 

Some small steps: I forked matteruser und had some success in adding the driver and managed to implement at least the login-procedure. I hope this could be the starting point for someone more knowledgable to coffee-/javascript ;-)

Cheers
TG

**Comment by loafoe** [comment]
@ThetaGamma ah great! Once I get the `3.5.0` release out I'll have a serious look at using the official Javascript driver, would definitely reduce the support surface area.

**Comment by it33** [comment]
We've been adding more and more to the API documentation at https://api.mattermost.com/

Any questions, please just ask us at https://pre-release.mattermost.com/core/channels/developers

Thanks for building a fantastic extension! We'd love to support you as you build further!

**Comment by loafoe** [comment]
@ThetaGamma we've switch to v4 API. Looks like the referenced Javascript driver is still at v3? I'll definitely accept PRs that switches us to the official driver but as of now I don't foresee having bandwidth to do this myself in the near future.
