### ISSUE TITLE
Matteruser fails to log in

### ISSUE THREAD

**Issue by downright770** [loafoe/hubot-matteruser#19]
I'm a bit new to linux and using hubot. 
I'm currently trying to get up and running hubot with matteruser adapter and I'm not sure if I'm way off with trying to configure it to work.

On a virtual machine 
I've setup a user and password for the robot in Mattermost
Then I've created shell script.
# !/bin/sh

export MATTERMOST_HOST=http/127.0.0.1:8065
export MATTERMOST_GROUP=internal
export MATTERMOST_USER=gizmo
export MATTERMOST_PASSWORD=secret

cd /home/spike/myhubot
bin/hubot --adapter matteruser > /var/log/hubot.log 2>&1

log file shows 

Fri Oct 14 2016 10:08:30 GMT-0700 (PDT)] INFO Logging in...
[Fri Oct 14 2016 10:08:31 GMT-0700 (PDT)] ERROR Login call failed
[Fri Oct 14 2016 10:08:31 GMT-0700 (PDT)] INFO Reconnecting in 1000ms
[Fri Oct 14 2016 10:08:32 GMT-0700 (PDT)] INFO Attempting reconnect

Any help would be great

**Comment by mgrodrigues** [comment]
Hi downright770,

I'm new to hubot too and i make it work yesterday.
I guess you are missing some variables. 

# Assuming your mattermost is accessible on port 8065
MATTERMOST_WSS_PORT=8065
# Should be the same as MATTERMOST_WSS_PORT
MATTERMOST_HTTP_PORT=8065
# if you are not using SSL certificates you must set the following 2 variables to false (default is true)
MATTERMOST_TLS_VERIFY=false
MATTERMOST_USE_TLS=false
# You may want to increase log level to have more details about what is happening
MATTERMOST_LOG_LEVEL=debug

Hope it helps

**Comment by downright770** [comment]
Tied that log file showing 
[Fri Oct 14 2016 14:50:09 GMT-0700 (PDT)] INFO Logging in...
[Fri Oct 14 2016 14:50:09 GMT-0700 (PDT)] DEBUG POST /users/login
[Fri Oct 14 2016 14:50:09 GMT-0700 (PDT)] ERROR Login call failed
[Fri Oct 14 2016 14:50:09 GMT-0700 (PDT)] INFO Reconnecting in 1000ms

**Comment by mgrodrigues** [comment]
You have a typo in MATTERMOST_HOST value. 
It should be : 
http://127.0.0.1:8065

**Comment by downright770** [comment]
yeah changed that here is the file 

#!/bin/sh 

export MATTERMOST_HOST=http//127.0.0.1:8065
export MATTERMOST_WSS_PORT=8065
export MATTERMOST_HTTP_PORT=8065
export MATTERMOST_TLS_VERIFY=false
export MATTERMOST_USE_TLS=false
export MATTERMOST_USER=gizmo
export MATTERMOST_PASSWORD=secret
export MATTERMOST_GROUP=internal
export MATTERMOST_LOG_LEVEL=debug


cd /home/spike/myhubot
bin/hubot --adapter matteruser > /var/log/hubot.log 2>&1

**Comment by downright770** [comment]
still not working though

**Comment by mgrodrigues** [comment]
Still a typo. You forgot the colon symbol after http

http://127.0.0.1:8065

Type that URL in your browser and ensure mattermost is up and running. 
Don't forget to source the file before running hubot.

**Comment by downright770** [comment]
Thank you for all the help 
I fixed my error but still getting login error.
I retested the password in my web browser and works fine.
When you did your user name did you do it as a email address at all.

**Comment by mgrodrigues** [comment]
You're welcome,

I created the user using the invite link. The email address I set is not a valid one.

For MATTERMOST_USER I've setup the email address not the uername. Give it a try and post the logs.

Also, MATTERMOST_GROUP should be used to setup the team name and not a private group.

**Comment by downright770** [comment]
Still getting logging in errors.
I've changed user to an email address and verified I could log in with it.
GROUP is correct.
here's the file. 

#!/bin/sh 

export MATTERMOST_HOST=http://127.0.0.1:8065
export MATTERMOST_WSS_PORT=8065
export MATTERMOST_HTTP_PORT=8065
export MATTERMOST_TLS_VERIFY=false
export MATTERMOST_USE_TLS=false
export MATTERMOST_USER=downright770@hotmail.com
export MATTERMOST_PASSWORD=Xirtam770
export MATTERMOST_GROUP=internal
export MATTERMOST_LOG_LEVEL=debug


cd /home/spike/myhubot
bin/hubot --adapter matteruser > /var/log/hubot.log 2>&1

Log file

Mon Oct 17 2016 09:52:28 GMT-0700 (PDT)] INFO Logging in...
[Mon Oct 17 2016 09:52:28 GMT-0700 (PDT)] DEBUG POST /users/login
[Mon Oct 17 2016 09:52:28 GMT-0700 (PDT)] ERROR Login call failed
[Mon Oct 17 2016 09:52:28 GMT-0700 (PDT)] INFO Reconnecting in 1000ms

**Comment by downright770** [comment]
So have got first part now just need it to connect to the room.
Can't have this 
export MATTERMOST_HOST=http://127.0.0.1:8065
needed to be 
export MATTERMOST_HOST=127.0.0.1

This is the new error
INFO Connecting...
[Mon Oct 17 2016 10:39:52 GMT-0700 (PDT)] ERROR Failed to get subscribed channels list from server.

**Comment by mgrodrigues** [comment]
You're right.
Well done. Congrats

Sorry to be insistent but i think that your MATTERMOST_GROUP variable is not set correctly.
This variable should point to your team name. Is your team named "internal" ?

somewhere in the logs you should see this kind of line 

```
[Mon Oct 17 2016 21:11:38 GMT+0200 (CEST)] DEBUG Found 1 teams.
[Mon Oct 17 2016 21:11:38 GMT+0200 (CEST)] DEBUG Testing mich == mich
```

**Comment by downright770** [comment]
No it has to be set to the url. So mine I had to change to inter

**Comment by loafoe** [comment]
@downright770 did you check the suggestion of @mgrodrigues ? The group detection should indeed show up in your logs. Please let us know, thx.
