### ISSUE TITLE
@hubot mentions should work

### ISSUE THREAD

**Issue by nickolasclarke** [loafoe/hubot-matteruser#20]
this would give similar functionality to what is seen with slackbot in slack. from what I've read searching around for this, the slack adapter supports this. With some guidance, I can probably tackle this as my first foray into hubot development.

**Comment by loafoe** [comment]
Hi @nickolasclarke , can you maybe point to a description of an explanation of the feature that you are requesting? Thanks!

**Comment by nickolasclarke** [comment]
@loafoe just as in github I can use use the following `@loafoe` to mention you (and can autcomplete your username) `@<hubot_name>` should also work as a response trigger. So instead of saying `hubot the rules` I could say `@hubot the rules`.

**Comment by loafoe** [comment]
@nickolasclarke this should already work! Just make sure that the bot is in the channel that you are typing `@<hubot_name>` in and also that the mention is at the beginning of your message.
