### ISSUE TITLE
response of the bot

### ISSUE THREAD

**Issue by smnmtzgr** [loafoe/hubot-matteruser#22]
Hi,

when executing a command to which to bot reacts/responses, I always get back the "id" of the bot-user first before the actual result follows.

For example: p93qj5g13tyj9fxktzg7ekctsr

Is it possible to disable this behaviour, for example with an additional environment variable? I only want the bot to reply with the result of my request.

Regards,
Simon

**Comment by loafoe** [comment]
@smnmtzgr this should not be happening. Can you share the hubot script that you are using that exhibits this behaviour? Thx!

**Comment by gajus** [comment]
I am experiencing the same behaviour:

```
14:32 @january help
January Jones:
14:32
@gg65tw6izifspgn31p44ipbioy january adapter - Reply with the adapter
january animate me <query> - The same thing as image me, except adds a few parameters to try to return an animated GIF instead.
january echo <text> - Reply back with <text>
january help - Displays all of the help commands that Hubot knows about.
january help <query> - Displays all help commands that match <query>.
january image me <query> - The Original. Queries Google Images for <query> and returns a random top result.
january map me <query> - Returns a map view of the area returned by query.
january mustache me <url|query> - Adds a mustache to the specified URL or query result.
january ping - Reply with pong
january pug bomb N - get N pugs
january pug me - Receive a pug
january the rules - Make sure hubot still knows the rules.
january time - Reply with current time
january translate me <phrase> - Searches for a translation for the <phrase> and then prints that bad boy out.
january translate me from <source> into <target> <phrase> - Translates <phrase> from <source> into <target>. Both <source> and <target> are optional
ship it - Display a motivation squirrel
```

**Comment by gajus** [comment]
All I have done is followed the instructions from https://hubot.github.com/docs/ + https://github.com/loafoe/hubot-matteruser. No custom scripts.

**Comment by loafoe** [comment]
@gajus @smnmtzgr ah I see. I've been using an older version of `hubot-help` which used the **send** method instead of the **reply** method in `0.2.0`. However, this version should use Mattermost username instead of the actual user id. 

- Which version of Hubot are you using? `2.19.0`?
- Which version of MatterMost server are you using? `3.5.0`?

**Comment by gajus** [comment]
The latest version of both.

**Comment by loafoe** [comment]
@gajus @smnmtzgr can you try to master branch of `hubot-matteruser`?

`git://github.com/loafoe/hubot-matteruser.git#master`

It contains some changes specifically for the reply behaviour.

**Comment by smnmtzgr** [comment]
I will try this... stay tuned.

**Comment by loafoe** [comment]
@smnmtzgr did it work?

**Comment by smnmtzgr** [comment]
It works. Thank you very much.
