### ISSUE TITLE
mattermost 3.6.1 is incompatible with hubot-matteruser 3.5.1

### ISSUE THREAD

**Issue by vikaskedia** [loafoe/hubot-matteruser#27]
Mattermost 3.6.1 just got launched.

What do I need to do to use hubot-matteruser 3.5.1 with mattermost 3.6.1 ?

**Comment by loafoe** [comment]
@vikaskedia `3.5.1` should still be compatible with mattermost `3.6.x`. I will release a `3.6.0` shortly though. Please let me know if you find any issues. As of now there are no specific changes going into the new release.
