### ISSUE TITLE
Support MatterMost 3.0 

### ISSUE THREAD

**Issue by mxiamxia** [loafoe/hubot-matteruser#3]
Could you please help to upgrade it to support Mattermost 3.0? The current one only work for Mattermost 2.x

**Comment by loafoe** [comment]
Hi @mxiamxia , there is already preliminary support for Mattermost 3.0 in the `v3` branch. I will create a release shortly

**Comment by loafoe** [comment]
Version 3.0.0 was just released which adds Mattermost 3.x support. Be sure to modify your existing Hubot `package.json` in case of an existing bot!
