### ISSUE TITLE
Join multiple teams

### ISSUE THREAD

**Issue by velinath** [loafoe/hubot-matteruser#36]
Hi,

Wondering if there is support for multiple teams in the matteruser plugin. I have multiple internal teams that it would be nice to integrate Hubot into, so if there is a way to do that without spinning up multiple Hubot instances that'd be awesome.

**Comment by velinath** [comment]
Never mind, just saw #15

**Comment by loafoe** [comment]
Yeah, sorry about that, the hubot internals are not conducive to the idea.
