### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by downright770** [loafoe/hubot-matteruser#37]
I was wondering if matteruser works with outgoing web hooks.

I'm trying to get hubot to listen on all channels with out having to invite to a channel.
The channels I'm looking to do this on are all public channels. 
I've tried creating a web hook and adding it into my export cmds in shell script, but 
can't seem to get anywhere.

Outgoing hook for public channels
Content-Type: application/x-www-form-urlencoded
Trigger Words: bot
Trigger When: First word matches a trigger word exactly
Token: secret 
Callback URLs: http://localhost:8080/bot/incoming

**Comment by loafoe** [comment]
@downright770 is the `/bot/incoming` endpoint a hubot listener endpoint? I have the following piece of code in one of my scripts that might work for you:

```coffeescript
qs         = require 'qs'

module.exports = (robot) ->
    robot.router.post '/bot/incoming', (req, res) ->
        cmd = qs.parse req.body
        robot.logger.info JSON.stringify(cmd)
        user = robot.brain.userForId cmd.user_id
        user.room = cmd.channel_id
        # .. Do some stuf here ..
        res.send '{ "response_type": "ephemeral", "text": "This is a response" }'
```

Now you can configure a slash command or outgoing webhook and point it to the above defined endpoint in your bot.

**Comment by downright770** [comment]
Hi, 

Sorry took so long to get back. 
I haven't set up an scripts, and I'm sorta new to this. 
I see that there is a example script. Would I have to write or copy scripts in to make certain calls.
