### ISSUE TITLE
Add reaction support

### ISSUE THREAD

**Issue by jwernicke** [loafoe/hubot-matteruser#41]
Mattermost now has beta reaction support. The [API reference for reactions](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1teams~1%7Bteam_id%7D~1channels~1%7Bchannel_id%7D~1posts~1%7Bpost_id%7D~1reactions~1save%2Fpost) and  [hubot-slack](https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee) might be helpful for implementing this feature.

**Comment by loafoe** [comment]
@jwernicke waiting for the reactions API to become available in the Mattermost `v4` API

**Comment by mmack** [comment]
I think it's available right? https://api.mattermost.com/#tag/reactions

**Comment by loafoe** [comment]
@jwernicke @mmack it's now available in `mattermost-client` as `react()` and `unreact()` calls, but I'm not sure these are exposed on the @robot object which is passed to your scripts. Would be great if you can try it out.

**Comment by reduckted** [comment]
I'm not 100% sure I'm looking in the right place, but I've created a tiny script to check if the `react()` and `unreact()` functions are available, and they don't seem to exist.

```js
module.exports = (robot) => {
  robot.hear(/hubot/, (res) => {
    console.log(res.robot.react);
  })
};
```
When it receives a command, it prints `undefined` to the console.

**Comment by reduckted** [comment]
Ah, I think I found them. The `mattermost-client` instance is available off the adapter, so you can do this:

```js
module.exports = (robot) => {
  robot.hear(/hubot/, (res) => {
        res.robot.adapter.client.react(res.message.id, 'paddlin');
  })
};
```

**Comment by loafoe** [comment]
@reduckted  thanks for checking!!

**Comment by jwernicke** [comment]
Works per @reduckted's suggestion.

```javascript
module.exports = (robot) => {
  robot.hear(/hubot/, (res) => {
    res.robot.adapter.client.react(res.message.id, 'paddlin');
  })
};
```
