### ISSUE TITLE
Question about external scripts

### ISSUE THREAD

**Issue by downright770** [loafoe/hubot-matteruser#42]
I'm able to get hubot up and running have a couple scripts that are working like youtube, etc.
but any scripts that don't need a token will not work.
I'm not sure if I'm missing something.

I have writen a shell file 
that runs hubot and external scripts

export HUBOT_YOUTUBE_API_KEY="secret"
any help would be great

**Comment by Judokus** [comment]
What errors do you get?

**Comment by downright770** [comment]
Don't get any errors just get no response in Mattermost when working with external scripts.
The test script works. So I'm lost does hubot need anything else to work with external scripts.

**Comment by Judokus** [comment]
Post your shell script

**Comment by downright770** [comment]
#!/bin/sh

export MATTERMOST_HOST=127.0.0.1
export MATTERMOST_WSS_PORT=8065
export MATTERMOST_HTTP_PORT=8065
export MATTERMOST_TLS_VERIFY=false
export MATTERMOST_USE_TLS=false
export MATTERMOST_USER=
export MATTERMOST_PASSWORD=
export MATTERMOST_GROUP=
export MATTERMOST_LOG_LEVEL=debug

#FOR HUBOT TO JOIN ALL PUBLIC CHANNELS
export MATTERMOST_ENDPOINT=bot/incoming
export MATTERMOST_INCOME_URL=http://localhost:8065/int1/channels/
export MATTERMOST_TOKEN=""


export HUBOT_DARK_SKY_API_KEY=
#export HUBOT_WOLFRAM_APPID=""
export HUBOT_IMGUR_CLIENT_ID=
export HUBOT_TIMEZONEDB_API_KEY=
export HUBOT_GOOGLE_CSE_ID=":"
export HUBOT_GOOGLE_CSE_KEY=""
export HUBOT_YOUTUBE_API_KEY="-"

export HUBOT_RELEVANT_XKCD



#export HUBOT_TWITTER_KEY=""
#export HUBOT_TWITTER_SECRET=""
#export HUBOT_TWITTER_TOKEN="806221525707735040-"
#export HUBOT_TWITTER_TOKEN_SECRET=""

#sleep 5min because we need to wait for MM to actually load and have no indicators
#sleep 300

cd /home/chat/mybot
bin/hubot --adapter matteruser #> /var/log/hubot.log 2>&1

**Comment by downright770** [comment]
Pulled all the information out and tokens etc .
