### ISSUE TITLE
Multiple "brain loaded" messages

### ISSUE THREAD

**Issue by xurizaemon** [loafoe/hubot-matteruser#43]
I'm observing issues where we see some plugins get loaded repeatedly - and alongside this I see repeats of the ["Brain loaded"](https://github.com/loafoe/hubot-matteruser/blob/master/src/matteruser.coffee#L100) message from matteruser.coffee

    [Thu Apr 27 2017 09:24:51 GMT+1200 (NZST)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
    [Thu Apr 27 2017 09:24:51 GMT+1200 (NZST)] INFO Brain loaded
    [Thu Apr 27 2017 09:24:51 GMT+1200 (NZST)] INFO Brain loaded
    [Thu Apr 27 2017 09:24:51 GMT+1200 (NZST)] INFO Brain loaded
    [Thu Apr 27 2017 09:24:52 GMT+1200 (NZST)] INFO Brain loaded
    [Thu Apr 27 2017 09:24:52 GMT+1200 (NZST)] INFO Brain loaded

Trying to identify what would cause this to happen, and wondering if other users are observing it also.

Related issue over in my bot repo: https://github.com/xurizaemon/bolts/issues/15

**Comment by Judokus** [comment]
From [brain.coffee](https://github.com/github/hubot/blob/master/src/brain.coffee)
Everytime you access brain.data it emits 'brain loaded' message. Just lower your log level if you don't want to see them.

**Comment by xurizaemon** [comment]
Thanks Judokus, appreciate you taking time to reply, and the pointer to those brain events was helpful. I'll update if I work out what's doing it.

**Comment by xurizaemon** [comment]
You beauty! It took time to percolate for me, but I finally saw it: [vspiewak/hubot-twitter-mentions](https://github.com/vspiewak/hubot-twitter-mention/blob/master/src/twitter-mention.coffee#L80) treats that "loaded" event as an "initialised" event, rather than a "data retrieved" event. Thanks again :)
