### ISSUE TITLE
`loggedIn` overrides bot name provided via `hubot --name NAME ...`

### ISSUE THREAD

**Issue by trentm** [loafoe/hubot-matteruser#48]
This line in `loggedIn` sets `robot.name` to the auth username:
  https://github.com/loafoe/hubot-matteruser/blob/4f560900146161521a2bbfb12f2cd517b6e8e47b/src/matteruser.coffee#L93
This overrides a value set via `hubot --name NAME ...`. 

Should that be a bug? It is for me, at least. At my company we use a corporate LDAP for auth to our Mattermost team. I want the bot to respond to the name "bot", but the access account given me by our operations team is "joybot2". In my copy of hubot-matteruser I remove this line (via this patch: https://gist.github.com/trentm/3decef3c09278b18863744759693af20).

I'm not sure if you'd consider this a bug for this project. Just removing this line would potentially (likely?) break existing users, so either you'd want to make it opt-in or do a major version bump.

Thanks for the library!

**Comment by loafoe** [comment]
@trentm this is a breaking change, but I agree that it should not ignore the --name variable. The instructions we provide generate a script with the `--name` parameter as default so I will remove the line and will document it in the release notes of the next major release, thanks!

**Comment by loafoe** [comment]
@trentm will be changed release `v4.1.0`
