### ISSUE TITLE
Show Channel Name

### ISSUE THREAD

**Issue by Nothingtoloose** [loafoe/hubot-matteruser#49]
Hello, 
thanks for your great hubot plugin.

For many plugins you need the room name. The method "context.response.message.room" outputs only the room ID. I've seen the Mattermost API has the ability to output the room name. Could you implement the function please?

**Comment by Nothingtoloose** [comment]
I solved the problem. Just create a new variable. I have added the following line in line 180:
user.room_name = msg.data.channel_display_name

The channel Name is now stored in the variable user.room_name

**Comment by loafoe** [comment]
@Nothingtoloose can you create a pull request for this? I'll merge it in the next release then. Thanks!

**Comment by loafoe** [comment]
Merged #51
