### ISSUE TITLE
Map me Preview

### ISSUE THREAD

**Issue by rgomez90** [loafoe/hubot-matteruser#54]
I recently installed hubot with the matteruser adapter. All works fine, but not the maps preview.

In your Readme-Example the bot response is just **one** image link.

If I ask my bot to map me sth. I get a response with **2** links, the "real" link (for which there is no preview available) and the image link (ending in "format=png").

Did you tweak your hubot for the example, so it only returns the image link or I am doing sth wrong here?

Here you have an example (link preview **is activated** in Mattermost):
![unbenannt](https://user-images.githubusercontent.com/12009909/31564889-202e3870-b065-11e7-9f0d-5edff131f779.PNG)

After asking to Mattermost devs they said : 

> Hubot should really embed that image using markup and make the image link to the map. Might be worth opening an issue on that repo.

I am just not sure if this is an issue of matteruser or hubot....

**Comment by loafoe** [comment]
hi @rgomez90 , the adapter is just pass through for the hubot plugins, it does not try to do anything smart. You should look at the implementation of the [hubot map me plugin](https://github.com/gkoo/hubot-maps)

Update: created a pull request :)

**Comment by rgomez90** [comment]
Thanks @loafoe
