### ISSUE TITLE
Feature request: OAuth2

### ISSUE THREAD

**Issue by pteichner** [loafoe/hubot-matteruser#55]
Is there any way to implement OAuth2 support. I'm unable to use matteruser as our mattermost instance is daisy chained with Oauth2

**Comment by loafoe** [comment]
@pteichner unfortunately OAuth2 is out of scope for the bot. However, my own company server setup in a similar way as yours, it's behind Gitlab Oauth2. So instead, you can just create a standard account with username/password using the Mattermost `platform` binary like so:

```
bin/platform user create --email some@email.com --username hubot --password S3cr3tPassw0rd 
```

Now you can use this account to login your Hubot, bypassing the OAuth2 flow. Hope this helps!
