### ISSUE TITLE
No response to channel

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [loafoe/hubot-matteruser#56]
Hi,

The adapter is able to add user successfully.

On issuing command from chat window - it shows the debug message as below but no feedback back to room. No matching like executing listener.

DEBUG Message {
  event: 'posted',
  data: 
   { channel_display_name: 'Town Square',
     channel_name: 'town-square',
     channel_type: 'O',
     post: '{"id":"3m3fzaragffymytc8b1zfa4amc","create_at":1510742604875,"update_at":1510742604875,"edit_at":0,"delete_at":0,"is_pinned":false,"user_id":"4h449hxdxtygddog1d14shfohy","channel_id":"han17huxebfufbed5fdoeowd3h","root_id":"","parent_id":"","original_id":"","message":"matteruser help","type":"","props":{},"hashtags":"","pending_post_id":"4h449hxdxtygddog1d14shfohy:1510742582275"}',
     sender_name: 'chatops',
     team_id: 'i84af7shmjgojchfom6xs9xq6y' },
  broadcast: 
   { omit_users: null,
     user_id: '',
     channel_id: 'han17huxebfufbed5fdoeowd3h',
     team_id: '' },
  seq: 3 }

**Comment by loafoe** [comment]
@SURAJTHEGREAT is the bot called `matteruser` or something else?

**Comment by SURAJTHEGREAT** [comment]
@loafoe  the bot is called as matteruser
As seen in below logs on running ./bin/hubot
[Thu Nov 16 2017 00:52:35 GMT-0500 (EST)] INFO hubot-redis-brain: Using default redis on localhost:6379

matteruser>

**Comment by SURAJTHEGREAT** [comment]
We were able to resolve the issue.
No code fix.
We had to login to different user to execute commands and not execute from bot user login.
