### ISSUE TITLE
hubot with matteruser adapter will not post to mattermost channel

### ISSUE THREAD

**Issue by EbsrVlee** [loafoe/hubot-matteruser#57]
Hi,

I can run hubot on a server external to the mattermost server. Hubot answers commands and responds appropriately. However, I cannot get hubot to post on the mattermost channel. 
Is there some logs I can look up or is there some advice you can give me?

I also noticed when I run ./bin/hubot --matteruser then ask hubot for the adapter it responds with shell.
I ran without the --matteruser and it stayed as shell.
Here is a screenshot.

Thanks. :)
![matteruser](https://user-images.githubusercontent.com/14913403/33148282-3cded300-cf99-11e7-8bff-b5df1ade054d.jpg)

- Victoria

**Comment by 3ch01c** [comment]
I believe the syntax is `bin/hubot --adapter matteruser`. `shell` is the default adapter.

**Comment by jwernicke** [comment]
I believe the syntax is `bin/hubot --adapter matteruser`. `shell` is the default adapter. It also looks like the default hubot web server port 8080 is in use so set the environment variable `PORT` to whatever you want to use instead for the web server. You can also delete `hubot-scripts.json` to get rid of that warning, and if you're not planning to use Heroku, you can delete the corresponding packages from `external-scripts.json` & `package.json` using the following two sed commands:

```
sed -i '/heroku/d' external-scripts.json
sed -i '/heroku/d' package.json
```

**Comment by ccoenen** [comment]
I think this can be closed?

**Comment by EbsrVlee** [comment]
Yes, please close. I ended up using golang-bot.
Thank you.





CONFIDENTIALITY NOTICE: The information in this e-mail, and any
attachment(s), may be confidential and legally privileged. It is
intended solely for the addressee(s). If you are not the intended
recipient, any disclosure, copying, distribution or any action taken or
omitted to be taken in reliance on this e-mail, is prohibited and may be
unlawful. If you received this e-mail message in error, immediately
notify the Eye-Bank POSTMASTER(postmaster@ebsr.org), and delete the
message from all e-mail client(s), inboxes and email receiving
systems(s) including copies archived in backup system(s).>>> Claudius
Coenen <notifications@github.com> 3/27/2018 6:17 AM >>>
I think this can be closed?

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/loafoe/hubot-matteruser/issues/57#issuecomment-376473032


If this is an unsolicited spam message, please click this link to
report it:
http://192.168.1.59:49285/contents/spamreport.shtml?rptid=85734&srvid=1b9vlnq
