### ISSUE TITLE
Regarding the 'slack-attachment' event - how to pass channelID

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [loafoe/hubot-matteruser#58]
We are calling the 'slack-attachment' event from the other hubot module to show message in the mattermost channel. We know only the channel name but in the slackAttachmentMessage method this is expecting channel ID so is it possible to include the channel name to channel ID logic inside the  slackAttachmentMessage  method itself.

Please help on this issue

**Comment by loafoe** [comment]
@SURAJTHEGREAT  please try the commit loafoe/mattermost-client@daa68fa in the driver. It contains code to convert `data.room` to a `channel_id` which should fix this for you.

**Comment by SURAJTHEGREAT** [comment]
@loafoe Thank you for the quick fix. This helps to fix my issue and Its working fine for me.
