### ISSUE TITLE
bot cannot ignore message from other bots in one channel

### ISSUE THREAD

**Issue by shipengqi** [loafoe/hubot-matteruser#59]
I invite two bots into one channel in same team, the bot cannot ignore messages from other bots
Steps to reproduce:

1. invite two bots (bot1, bot2) into one channel.
2. @bot1 {message}
3. bot1 reply message
4. bot2 will receive message which reply from bot1

Expected result:
bot2 ignore messages from other bot1

**Comment by loafoe** [comment]
hi @shipengqi , this is not something we can address at the adapter layer. Since your bots are separate processes there is no way they can know about each other except if you somehow encode this in e.g. q plugin that you install in both bots and cross configure them.
