### ISSUE TITLE
Channel name instead of ID?

### ISSUE THREAD

**Issue by alexiri** [loafoe/hubot-matteruser#6]
Is it possible to get the channel name instead of the channel id? The id isn't very useful...

**Comment by Judokus** [comment]
Method `findChannelByName` is in the mattermost-client. It returns the channel object. See [here](https://github.com/loafoe/mattermost-client/blob/master/src/client.coffee#L264)

**Comment by alexiri** [comment]
That function does the exact opposite of what would be needed. You could have pointed to `getChannelByID`, which is closer to my question.

Regardless, I realize now that my question was badly explained. When other hubot plugins (such as hubot-seen, for example) get the channel information, they get the channel id. They then print this information to the user, which is pretty useless:

`
> $ hubot seen alex
hubot: alex was last seen in dmmmhorgtfdq8yeotaaqdub71c at Fri Jun 24 2016 08:58:56 GMT+0200 (CEST)
`

**Comment by loafoe** [comment]
You would need to have a modified `seen` plugin that does the reverse lookup. Mattermost has chosen to work with non-hum consumable channel IDs
