### ISSUE TITLE
HUBOT UNABLE TO POST MESSAGE TO  MATTERMOST DYNAMIC CHANNEL UNLESS RESTART

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [loafoe/hubot-matteruser#60]
Hi Team,

I could observe that the messages posted to the new dynamically created mattermost channel does not reflect unless the hubot service is restarted

Steps to reproduce the issue:
1. Create a channel dynamically
2. Post message to channel from HUBOT - does not display the message in the channel
3. Post the message again after restart of Hubot - now displays message in the channel

Seems like the newly created dynamically channel is not discovered by hubot .

Please look into it and advice.

Thanks in advance.

Thanks,
Suraj S

**Comment by loafoe** [comment]
@SURAJTHEGREAT I've seen this myself. I think the internal channel is not properly updated by the `mattermost-client` part. It definitely looks like bug.

**Comment by Judokus** [comment]
I can not reproduce this. @SURAJTHEGREAT Can you show your script?

**Comment by loafoe** [comment]
thanks @Judokus !
