### ISSUE TITLE
Hubot Failed to log to Mattermost Chat

### ISSUE THREAD

**Issue by Hhhly** [loafoe/hubot-matteruser#61]
Hello all,

When i try to launch hubot in Mattermost I got this error : 

```
 ./bin/hubot --adapter matteruser


npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.

up to date in 1.664s
[Tue Jan 16 2018 13:48:59 GMT+0100 (CET)] INFO Logging in...
[Tue Jan 16 2018 13:48:59 GMT+0100 (CET)] INFO api url:https://182.21.221.170::8065/api/v4/users/login
[Tue Jan 16 2018 13:48:59 GMT+0100 (CET)] ERROR Login call failed
[Tue Jan 16 2018 13:48:59 GMT+0100 (CET)] INFO Reconnecting in 1000ms
[Tue Jan 16 2018 13:49:00 GMT+0100 (CET)] INFO Attempting reconnect
[Tue Jan 16 2018 13:49:00 GMT+0100 (CET)] INFO Logging in...
[Tue Jan 16 2018 13:49:00 GMT+0100 (CET)] INFO api url:https://182.21.221.170::8065/api/v4/users/login
[Tue Jan 16 2018 13:49:00 GMT+0100 (CET)] ERROR Login call failed
[Tue Jan 16 2018 13:49:00 GMT+0100 (CET)] INFO Reconnecting in 2000ms
^C


```

My variable are :

```
env | grep MATT*

MATTERMOST_HOST=182.21.221.170:8065
MATTERMOST_PASSWORD=mypassword
MATTERMOST_GROUP=myteam
MATTERMOST_USER=myuser
```

Hubot and Mattermost are on the same machine and when i try to connect directly with the user it works, but when i try to connect using Hubot it don't work and i get the error above.

Can someone help me with this plz ?

**Comment by Judokus** [comment]
Noticed the double colons showing up in your log (ip::port) 

Try `MATTERMOST_HOST=182.21.221.170` and specify your ports with: 
`MATTERMOST_HTTP_PORT` and/or `MATTERMOST_WSS_PORT`

... If it's on the same host I guess you could even do `MATTERMOST_HOST=127.0.0.1`

**Comment by Hhhly** [comment]
Thanks for your response.

I tried to add the port variable and after i tried my localhost ip nothing change ... 

```
[Tue Jan 16 2018 14:53:14 GMT+0100 (CET)] INFO Logging in...
[Tue Jan 16 2018 14:53:14 GMT+0100 (CET)] INFO api url:https://127.0.0.1:8065/api/v4/users/login
[Tue Jan 16 2018 14:53:14 GMT+0100 (CET)] ERROR Login call failed
[Tue Jan 16 2018 14:53:14 GMT+0100 (CET)] INFO Reconnecting in 1000ms

```

I keep searching.
Thanks for your help.

**Comment by Hhhly** [comment]
My Mattermost server is on HTTP and not on HTTPS , maybe it's that ? 

How can i change the way Hubot connect to the mattermost IP ?

**Comment by Hhhly** [comment]
I change some var and get the right call to HTTP but still got the error : 

```
npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.

up to date in 1.517s
[Tue Jan 16 2018 16:09:39 GMT+0100 (CET)] INFO Logging in...
[Tue Jan 16 2018 16:09:39 GMT+0100 (CET)] INFO api url:**_http_**://182.21.221.170:8065/api/v4/users/login
[Tue Jan 16 2018 16:09:40 GMT+0100 (CET)] ERROR Login call failed
[Tue Jan 16 2018 16:09:40 GMT+0100 (CET)] INFO Reconnecting in 1000ms
^C



```

**Comment by Judokus** [comment]
If it's on the same host `MATTERMOST_HOST=127.0.0.1` should work. TLS is enabled by default.
What do you get when you set `MATTERMOST_LOG_LEVEL=debug` ?

**Comment by Hhhly** [comment]
Ok it works now.

Thanks for your answer !
