### ISSUE TITLE
Message didn't deliver

### ISSUE THREAD

**Issue by bgualda** [loafoe/hubot-matteruser#65]
Hi guys,
I have configured in my docker-compose.sh information to start hubot-matteruser, but when I send a message like _hubot help_ the message didn't delivery.

Below, follow my configuration. 
  hubot-matteruser:
    build:
     context: ./hubot-matteruser
     args:
       hubot_owner: admin
       hubot_name: hubot
       hubot_description: GitGameBot
    restart: always
    user: hubot-matteruser
    links:
      - web:web
    ports:
      - "8080:8080"
    environment:
      - MATTERMOST_HOST=myIP
      - MATTERMOST_PORT=myPort
      - MATTERMOST_GROUP=myTime
      - MATTERMOST_USER=myEmailUser
      - MATTERMOST_PASSWORD=myPassword
      - MATTERMOST_LOG_LEVEL=debug
      - MATTERMOST_USE_TLS=false
      - MATTERMOST_TLS_VERIFY=false
      - MATTERMOST_WSS_PORT=80

And log, doesn't have any information about error:
Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Logging in...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG POST /users/login
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users/login
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Websocket URL: ws://192.168.57.65:8090/api/v4/websocket
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Logged in as user "hubot" but not connected yet.
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users/me
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users/me
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users/me
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users/me/preferences
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users/me/preferences
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users/me/preferences
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users/me/teams
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users/me/teams
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users/me/teams
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loaded Preferences...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loaded Me...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Found 1 teams.
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG Testing accurate == accurate
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Found team! 8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users?page=0&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users?page=0&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users?page=0&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users/me/teams/8s6rdaqubids58fydzriexnhqc/channels
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users/me/teams/8s6rdaqubids58fydzriexnhqc/channels
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users/me/teams/8s6rdaqubids58fydzriexnhqc/channels
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Connecting...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Connected to Mattermost.
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Sending challenge...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Starting pinger...
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Mattermost server: 4.9.0.4.9.0.d39ed1f8abee5df86e3d38e503512310.false
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG Received unhandled message:
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG { status: 'OK', seq_reply: 1 }
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Found 3 subscribed channels.
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Found 60 profiles.
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO Loading /users?page=1&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] DEBUG GET /users?page=1&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:55 GMT+0000 (UTC)] INFO api url:http://192.168.57.65:8090/api/v4/users?page=1&per_page=200&in_team=8s6rdaqubids58fydzriexnhqc
[Wed Apr 18 2018 17:17:56 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379

Someone can help me ?

**Comment by Fabianski-tr** [comment]
Have you tried running hubot directly from the same container in which you run Mattermost?

I've managed to make it work without any problems.

**Comment by loafoe** [comment]
@bgualda please try the new v5.0.0 release and report any issues
