### ISSUE TITLE
After the container is restarted, the reminders are deleted

### ISSUE THREAD

**Issue by negativ72rus** [loafoe/hubot-matteruser#70]
After the container is restarted, the reminders are deleted. Where does he store them?

**Comment by negativ72rus** [comment]
Hi! 
This. https://github.com/mx4492/hubot-remind-her
Unfortunately, the developer did not respond to my request.

**Comment by loafoe** [comment]
@negativ72rus 

https://github.com/mx4492/hubot-remind-her/blob/3e6e097126e06fb462121caa39c7b7bc3ffce57c/scripts/remind-her.coffee#L46

Looks like it supports `hubot.brain` so if you use below plugin then your data should be persisted to Redis and survive a restart:

https://github.com/hubotio/hubot-redis-brain
