### ISSUE TITLE
Bot not respon a request from mattermost

### ISSUE THREAD

**Issue by centen** [loafoe/hubot-matteruser#73]
hi,
i'm trying to configure the bot to make chatops
i build hubot matteruser on docker container
but i'm got some error, when call the bot to respon my order in mattermost don't show any respon
but in hubot logs, i got some error like this

![image](https://user-images.githubusercontent.com/19315902/43750479-d35fd8de-9a22-11e8-8031-cb07d3abe9b3.png)
![image](https://user-images.githubusercontent.com/19315902/43750505-f5bfbb42-9a22-11e8-9c37-4687f5b7021d.png)

any one please can help me, with this problem
thanks

**Comment by loafoe** [comment]
Hi @centen , looks like something is going wrong with loading the profiles. I have not tested the bot with Mattermost 5.2.0 yet though. you might have luck with an older version of the Mattermost server. I will try to look into in the next couple of days.

**Comment by bmaynard** [comment]
I am also experiencing the same issue. Running Mattermost v4.10.1

**Comment by thomasbellois** [comment]
Hello, me too. 
But I haven't the issue when I don't run it in container. 
Version: 4.8.0 of Mettermost

**Comment by centen** [comment]
@thomasbellois if I may know,
that you don't run in a container, it mattermost or the hubot?
Thanks

**Comment by thomasbellois** [comment]
@centen the goal is to run all on Docker. 
Mattermost is already on. 
I tested hubot with matteruser without "containerizing" it. The result was OK. 
I tryed on Docker but I have the error. However, I use the same connection parameters for the bot.

**Comment by mechanicjay** [comment]
Same issue here.  Mattermost 4.9, running hubot with docker-compose.

**Comment by sunnythaper** [comment]
Ah, I responded in another issue but I am having the same problem myself: https://cl.ly/340J1S3x0k1h

**Comment by loleg** [comment]
Not working out of the box, 4.10.1. I suspect (due to `matteruser.coffee:201:36` in the exception) this is caused by an old version of the client being loaded in the Docker script.

**Comment by codeart1st** [comment]
`generator-hubot` uses the latest published version of the adapter. And the latest version of `hubot-matteruser` has the .coffee script instead of the newer .js variant. So all what we need is a new release

**Comment by rgomez90** [comment]
@codeart1st is right.

Npm package, which is used by yo generator, use v 4.4.0, which has old `.coffee` file.

If you change (old) `matteruser.coffee` by (new, available here in Github repo) `matteruser.js` all works as expected in the newer Matttermost versions.

@loafoe could you please take a look on adding a new release? 😃

**Comment by thomasbellois** [comment]
I tried to replace the matteruser file by doing this

```
RUN echo no | yo hubot --adapter=matteruser --name="${hubot_name}" --owner="${hubot_owner}" --description="${hubot_description}"
RUN rm /usr/src/${hubot_name}/node_modules/hubot-matteruser/src/matteruser.coffee
RUN wget https://github.com/loafoe/hubot-matteruser/blob/master/src/matteruser.js -P /usr/src/${hubot_name}/node_modules/hubot-matteruser/src/
```

 but I get this error: 
```
body-parser deprecated undefined extended: provide extended option node_modules/hubot/src/robot.js:445:21
[Tue Sep 11 2018 12:47:40 GMT+0000 (UTC)] ERROR Cannot load adapter matteruser - SyntaxError: Unexpected token <
```

**Comment by mechanicjay** [comment]
Confirmed this is working.  I updated my Dockerfile to remove the .coffee and shove a copy of the .js file in the right place.

**Comment by rgomez90** [comment]
@loafoe what about the new release?
**This repo is not usable for now without manual changes**...
Last commit was 3 months ago, is someone supporting/taking care of this repo?

**Comment by loafoe** [comment]
@centen @rgomez90 @mechanicjay @loleg @thomasbellois @bmaynard there ia new major release available which should fix the issue. As the new release is ES6 there might be some incompatibilities with some existing scripts. Please try the new release and report any issues. And apologies for the delay.
