### ISSUE TITLE
Caret range specifier breaks legacy clients

### ISSUE THREAD

**Issue by contolini** [loafoe/hubot-matteruser#8]
Hi @loafoe!

After trying to figure out why our bot was mysteriously crashing, I noticed [`v3.1.1` of this plugin](https://github.com/loafoe/hubot-matteruser/blob/v3.1.1/package.json#L31) lists version `^3.1.1` of mattermost-client as a dependency. Now that version 3.3.x of mattermost-client has been released, hubot-matteruser is pulling it in, causing it to fail because there are backwards-incompatible changes in 3.3.x. (Our server is still at MM v3.2)

Instead, the mattermost-client dep should probably be listed with a tilde ~ range specifier so that only patch increments are included.

cc @higs4281

**Comment by loafoe** [comment]
Thx @contolini! fixed in `3.3.1`
