### ISSUE TITLE
Interactive dialogs

### ISSUE THREAD

**Issue by tomer953** [loafoe/hubot-matteruser#81]
https://docs.mattermost.com/developer/interactive-dialogs.html

hey, any chance to support dialogs ?
(if already possible, an example could be nice)

Thank you!

**Comment by tomer953** [comment]
I made a PR to the mattermost-client project:
https://github.com/loafoe/mattermost-client/pull/55/commits

**Comment by loafoe** [comment]
Thanks @tomer953 , I created a new release with your PR and will also release a new version of the adapter shortly

**Comment by loafoe** [comment]
v5.3.0 is available now
