### ISSUE TITLE
Feature Request: mattermost-client to mattermost-client-node

### ISSUE THREAD

**Issue by mlmnetcologne** [loafoe/hubot-matteruser#88]
Hi,

as I can see, is the https://github.com/loafoe/mattermost-client not well mantained. (https://github.com/loafoe/mattermost-client/pull/118#issuecomment-580316749) 
So it would be nice when this project migrate to mattermost-client-node.

Greetings,

Maurice

**Comment by jwernicke** [comment]
If @loafoe's response time to your merge requests doesn't meet your threshold for "well maintained", it might make more sense to maintain your own fork of this project which uses @bitExpert's fork of mattermost-client.

**Comment by mlmnetcologne** [comment]
With "well maintained" I mean, that the @bitExpert's fork is more often updated and improved, with tests and so on. Yeah, it is possible to add another fork to the world, but it's not necessary. But as long as I can't use @bitExpert's fork, I have to set the project on hold. I had the last months not much time, but as I remember, there are some problems.
The response time is not my threshold for "well maintained, as long its usable. (Not broken, as it is said in the comment.)

Just asking for help,

Maurice

ps: could you please just add something productive and helpful instead of that. thank you.

**Comment by loafoe** [comment]
@mlmnetcologne the thing is the @bitExpert guys came here a few months as part of some Hacktoberfest initiative, offered to add tests and improve the project, I gave them contributor rights. They then proceeded to add some skeleton test framework code without ever getting to a green build. So from that point the project builds fail miserably and then they decided to fork off and are now claiming this project is broken 🤣🙄👎

I will try to spend some time in the next few days creating to see if I can get a new release of both projects out. Any help appreciated 👍
