### ISSUE TITLE
hubot replies result in "Invalid RootId parameter" messages and no output

### ISSUE THREAD

**Issue by rickknowles-cognitant** [loafoe/hubot-matteruser#96]
Hi,

When I use hubot to reply with "res.reply()" I've recently started getting no output and this message appearing in the mattermost logs.

{"level":"error","ts":1599811356.7178369,"caller":"mlog/log.go:190","msg":"Invalid RootId parameter.","path":"/api/v4/posts","request_id":"br7m7m48ybyhmj14d6ji5pnq8e","ip_addr":"82.5.211.17","user_id":"bub31doftbbe9fuggmdnshwywr","method":"POST","err_where":"createPost","http_code":400,"err_details":""}

Any ideas ? This wasn't happening a few versions ago. I'm using 5.4.0, but the same thing happened on 5.3.1

**Comment by rickknowles-cognitant** [comment]
I came across this post from a similarly described error in another project in case it helps:

https://github.com/42wim/matterbridge/issues/803

The fix was:

https://github.com/42wim/matterbridge/commit/0b03076a9dd411e567a06f231302f65d95e78c41

**Comment by loafoe** [comment]
hi @rickknowles-cognitant I don't have direct access to a mattermost server at this time to replicate the issue but will try to understand the issue in the next couple of days

**Comment by rickknowles-cognitant** [comment]
OK sure thanks. In the meantime I've narrowed it down to being something that was introduced between v5.3.1 and v5.4.0. 

I force the install of mattermost-client-6.2.0 with hubot-matteruser 5.3.1 and the problem didnt happen, so I'm fairly confident diffing those two versions of hubot-matteruser is a good place to start

HTH

**Comment by rickknowles-cognitant** [comment]
Based on the error message, I'd be almost certainly willing to be it's this:

![image](https://user-images.githubusercontent.com/37247203/92913580-cdf9ff80-f422-11ea-86de-89c497399229.png)

**Comment by rickknowles-cognitant** [comment]
If anyone else needs a quick workaround, just change your package.json to this temporarily (note the lack of carets on package versions):

{
  "dependencies": {
    "hubot-matteruser": "5.3.1",
    "mattermost-client": "6.2.0"
  }
}

Confirmed it worked for me

**Comment by loafoe** [comment]
@jgarec any thoughts on this?

**Comment by rickknowles-cognitant** [comment]
Sorry forgot to mention the mattermost versions I tested this with were v5.22 and v5.26

**Comment by jgarec** [comment]
Hi

Could you give me more details ?
Is it a direct message or on a channel ?
Could you paste a minimalist hubot script to reproduce ?

Thx

**Comment by jgarec** [comment]
Sorry, there was a little error in my previous PR

**Comment by loafoe** [comment]
thanks for fixing @jgarec 

@rickknowles-cognitant version 5.4.1 should contain the fix for this
