### ISSUE TITLE
Need correction on channel name

### ISSUE THREAD

**Issue by ecylmz** [loafoe/hubot-matteruser#98]
Hi,

I saw this PR: https://github.com/loafoe/hubot-matteruser/pull/51

I need `channel_name`. `channel_display_name` doesn't give the value what i want. `channel_name` is required when making webhook requests. "Channel display name" and "Channel name" are different. They don't give the same value.

For example on DM:

Channel display name: `@user`
channel_name: `tay1jmy83brcbxq14hs6jmucsy__tptwwehd33bspge31scb5frtxh`

You need to `channel_name` value when you want to send something to this conversation via webhook.

So, i think this [line](https://github.com/loafoe/hubot-matteruser/blob/master/src/matteruser.js#L348) should be:

```js
user.room_name = msg.data.channel_name
```

or

```js
user.room_name = msg.data.channel_name
user.room_display_name = msg.data.channel_display_name
```

WDYT?

Thanks.

**Comment by loafoe** [comment]
Please create a PR and if you can confirm it works we will definitely consider merging 👍
